package ParkirPelabuhan;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fardan
 */
public class InputForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputForm.class.getName());
    private LarikKendaraan larikKendaraan;

    /**
     * Creates new form InputForm
     */
    public InputForm(LarikKendaraan larikKendaraan) {
        this.larikKendaraan = larikKendaraan;
        initComponents();
        setupEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jenisKendaraanBox = new javax.swing.JComboBox<>();
        jenisParkirBox = new javax.swing.JComboBox<>();
        jenisParkirLabel = new javax.swing.JLabel();
        jenisKendaraanLabel = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        judulLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 230));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Nama Pemilik:");

        jLabel4.setText("NIK:");

        jenisKendaraanBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor", "Truk" }));
        jenisKendaraanBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKendaraanBoxActionPerformed(evt);
            }
        });

        jenisParkirBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Menginap" }));
        jenisParkirBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisParkirBoxActionPerformed(evt);
            }
        });

        jenisParkirLabel.setText("Jenis Parkir");

        jenisKendaraanLabel.setText("Jenis Kendaraan:");

        jLabel5.setText("No Plat:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jenisParkirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jenisKendaraanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jenisParkirBox, 0, 97, Short.MAX_VALUE)
                            .addComponent(jenisKendaraanBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKendaraanBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenisKendaraanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisParkirBox)
                    .addComponent(jenisParkirLabel))
                .addGap(12, 12, 12))
        );

        okButton.setText("OK");

        judulLabel.setText("Input Kendaraan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(okButton)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisParkirBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisParkirBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisParkirBoxActionPerformed

    private void jenisKendaraanBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKendaraanBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisKendaraanBoxActionPerformed

     private void setupEventListeners() {
        okButton.addActionListener(evt -> {
            simpanKendaraan();
        });
    }
    
    private void simpanKendaraan() {
        try {
            // Validasi input
            String namaPemilik = jTextField1.getText().trim();
            String nik1 = jTextField3.getText().trim();
            String nik2 = jTextField4.getText().trim();
            
            if (namaPemilik.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama pemilik harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (nik1.isEmpty() || nik2.isEmpty()) {
                JOptionPane.showMessageDialog(this, "NIK harus diisi lengkap!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Buat objek Person
            Person pemilik = new Person();
            pemilik.setNama(namaPemilik);
            pemilik.setAlamat(nik1); // Menggunakan field nik pertama sebagai alamat sementara
            
            // Tentukan jenis kendaraan
            String jenisKendaraan = (String) jenisKendaraanBox.getSelectedItem();
            Kendaraan kendaraan = null;
            
            switch (jenisKendaraan) {
                case "Motor":
                    kendaraan = new Motor();
                    break;
                case "Mobil":
                    kendaraan = new Mobil();
                    break;
                case "Truk":
                    kendaraan = new Truk();
                    break;
            }
            
            if (kendaraan == null) {
                JOptionPane.showMessageDialog(this, "Jenis kendaraan tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Set data kendaraan
            kendaraan.setPemilik(pemilik);
            kendaraan.setNoKendaraan(nik2); // Menggunakan nik2 sebagai nomor plat
            
            // Set status parkir
            String jenisParkir = (String) jenisParkirBox.getSelectedItem();
            kendaraan.setStatus(jenisParkir.equals("Menginap") ? 1 : 0);
            
            // Set waktu datang (sekarang)
            Waktu waktuDatang = new Waktu(new Date(), new Time());
            waktuDatang.getDate().setNow();
            waktuDatang.getTime().setNow();
            kendaraan.setWaktuDatang(waktuDatang);
            
            // Set waktu pulang (default sama dengan waktu datang, akan diupdate saat keluar)
            Waktu waktuPulang = new Waktu(new Date(), new Time());
            waktuPulang.getDate().setNow();
            waktuPulang.getTime().setNow();
            kendaraan.setWaktuPulang(waktuPulang);
            
            // Tambahkan ke larik kendaraan
            larikKendaraan.tambahKendaraan(kendaraan);
            
            JOptionPane.showMessageDialog(this, 
                "Kendaraan berhasil ditambahkan!\n" +
                "No. Plat: " + kendaraan.getNoKendaraan() + "\n" +
                "Jenis: " + jenisKendaraan + "\n" +
                "Waktu Masuk: " + waktuDatang.getDate() + " " + waktuDatang.getTime(),
                "Berhasil", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Reset form
            jTextField1.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jenisKendaraanBox.setSelectedIndex(0);
            jenisParkirBox.setSelectedIndex(0);
            
            // Tutup form
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> jenisKendaraanBox;
    private javax.swing.JLabel jenisKendaraanLabel;
    private javax.swing.JComboBox<String> jenisParkirBox;
    private javax.swing.JLabel jenisParkirLabel;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
