package ParkirPelabuhan;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fardan
 */
public class KeluarForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KeluarForm.class.getName());
    private LarikKendaraan larikKendaraan;
    /**
     * Creates new form InputForm
     */
    public KeluarForm(LarikKendaraan larikKendaraan) {
        this.larikKendaraan = larikKendaraan;
        initComponents();
        setupEventListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        judulLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 230));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("No. Plat:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        okButton.setText("OK");

        judulLabel.setText("Keluar Kendaraan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupEventListeners() {
        okButton.addActionListener(evt -> {
            keluarkanKendaraan();
        });
    }
    
    private void keluarkanKendaraan() {
        try {
            String noPlat = jTextField1.getText().trim();
            
            if (noPlat.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Nomor plat harus diisi!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Cari kendaraan berdasarkan nomor plat
            Kendaraan[] kendaraanArray = larikKendaraan.getKendaraan();
            int index = larikKendaraan.getIndex();
            int foundIndex = -1;
            
            for (int i = 0; i < index; i++) {
                if (kendaraanArray[i].getNoKendaraan().equalsIgnoreCase(noPlat)) {
                    foundIndex = i;
                    break;
                }
            }
            
            if (foundIndex == -1) {
                JOptionPane.showMessageDialog(this, 
                    "Kendaraan dengan nomor plat " + noPlat + " tidak ditemukan!", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Update waktu pulang
            Kendaraan kendaraan = kendaraanArray[foundIndex];
            Waktu waktuPulang = new Waktu(new Date(), new Time());
            waktuPulang.getDate().setNow();
            waktuPulang.getTime().setNow();
            kendaraan.setWaktuPulang(waktuPulang);
            
            // Hitung biaya
            int biaya = kendaraan.hitungBiaya();
            Time lamaJam = kendaraan.lamaJam();
            int lamaHari = kendaraan.lamaHari();
            
            // Tampilkan informasi pembayaran
            String info = String.format(
                "=== INFORMASI PEMBAYARAN ===\n\n" +
                "No. Plat: %s\n" +
                "Jenis Kendaraan: %s\n" +
                "Jenis Parkir: %s\n\n" +
                "Waktu Masuk: %s %s\n" +
                "Waktu Keluar: %s %s\n\n" +
                "Lama Parkir:\n" +
                "  - Hari: %d hari\n" +
                "  - Jam: %02d:%02d:%02d\n\n" +
                "TOTAL BIAYA: Rp %,d",
                kendaraan.getNoKendaraan(),
                kendaraan.getClass().getSimpleName(),
                kendaraan.getStatusString(),
                kendaraan.getWaktuDatang().getDate(),
                kendaraan.getWaktuDatang().getTime(),
                waktuPulang.getDate(),
                waktuPulang.getTime(),
                lamaHari,
                lamaJam.getJam(), lamaJam.getMenit(), lamaJam.getDetik(),
                biaya
            );
            
            JOptionPane.showMessageDialog(this, 
                info,
                "Pembayaran Parkir", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Hapus kendaraan dari array
            for (int i = foundIndex; i < index - 1; i++) {
                kendaraanArray[i] = kendaraanArray[i + 1];
            }
            kendaraanArray[index - 1] = null;
            larikKendaraan.setIndex(index - 1);
            
            // Reset form dan tutup
            jTextField1.setText("");
            this.dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
